/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Principal;

public class App {
    public String getGreeting() {
        return "Olá Mundo" + "Meu segundo comando de saída"; //Soma de duas strings retorna string!! mto bom!
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
